# Generated by Django 2.0 on 2018-04-19 07:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20180419_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldborder',
            name='mpoint',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
