# Generated by Django 2.0 on 2018-04-19 14:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20180419_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborder',
            name='mpoint',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='name',
        ),
        migrations.AddField(
            model_name='worldborder',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='idreg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='province',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='region',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
